# commands
# - brew bundle install         # install everything in this file
# - brew bundle cleanup         # see stuff installed that's not in this file
# - brew bundle cleanup --force # to remove that stuff

tap "homebrew/bundle"
tap "homebrew/services"

# tools
brew "eza" # ls replacement
brew "fd" # find replacement
brew "fish" # shell
brew "fzf" # fuzzy finder
brew "gh" # github cli
brew "git-delta" # git diff viewer
brew "jo" # write json from the command line
brew "jq" # json selector
brew "just" # task runner
brew "pgcli" # auto-complete for psql
brew "ripgrep" # grep replacement
brew "schpet/tap/envset" # updates .env files
brew "sd" # sed replacement
brew "starship" # shell prompt PS1 thing
brew "stow" # symlink manager, for dotfiles
brew "yazi" # file browser

# programming
brew "deno" # imagine if node was fun
brew "fnm" # node version manager
brew "rbenv" # ruby version manager
brew "rubyfmt" # ruby formatter extraordinaire

# mac os odds and ends
brew "cdrtools" # burn a cd from the cli
brew "switchaudio-osx" # lets you switch audio input/output from the command line

# basics
brew "coreutils" # real variants of sed, grep, etc
brew "curl" # use up-to-date curl
brew "ffmpeg" # convert my media
brew "git" # use up-to-date git
brew "libpq" # postgresql stuff?
brew "neovim" # vim replacement
brew "redis"
brew "sqlite" # a great database
brew "tmux" # not much of a reason to run this locally
brew "vips" # image processing library
brew "rsync"

# 3rd party services
brew "awscli" # script aws so i don't have to use their website
brew "flyctl" # fly.io cli
brew "heroku/brew/heroku" # heroku cli
brew "stripe/stripe-cli/stripe" # stripe cli

# gui apps
cask "alt-tab" # prefer this over mac os's command-tab (shows a vertical list with window titles)
cask "cog" # plays flac files
cask "docker" # container stuff
cask "ghostty" # terminal emulator
cask "musicbrainz-picard" # music tagger and organizer
cask "raycast" # spotlight replacement
cask "rectangle" # window manager
cask "zed@preview" # text editor
