# https://aider.chat/docs/config/aider_conf.html

attribute-commit-message-author: true
dark-mode: true
code-theme: solarized-dark
watch-files: true
read: ~/.config/aider/GLOBAL_CONVENTIONS.md

# model: sonnet
model: gemini/gemini-2.5-pro-preview-05-06
# model: o4-mini # cheaper, below gemini
# model: o3 # expensive, top of leaderboard
