
help:
    just -g -l -u

heroku-deploy-branch-staging:
    git push -f staging $(git branch --show-current):main

heroku-deploy-branch-production:
    git push -f production $(git branch --show-current):main
