[package]
name = "sluggy"
version = "0.1.0"
authors = ["Peter Schilling <peter@peterschilling.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slug = "0.1.4"
