#!/bin/bash

# this would be better if it was more generic
# e.g. 
#   agg ag my_search  (repeats ag my_search -l)
#   agg g s (repeats git status --porcelain | sed s/^...//')

ag "$@"
LIST_FILES='ag -l "$@"'

read -p "run a command on one of these files? (default: $EDITOR) " cmd

if [ "$cmd" == "" ] ;then
  $EDITOR $(eval $LIST_FILES | selecta)
else 
  $cmd $(eval $LIST_FILES | selecta)
fi
