#!/bin/bash

set -e

if [[ `git status --porcelain` ]]; then
  echo "you have unsaved changes:"
  echo
  git status --porcelain
  echo
  echo "commit them before linting"
  exit 1
fi

if [[ `bundle exec rubocop -a` ]]; then
  echo 'rubocop succeeded'
else
  echo "was not able to fix all rubocop errors automatically"
fi

yarn run eslint -- app/javascript --fix

git add --all
git commit -m "Automatically fix linter errors via \`./bin/autolint\`"
