#!/usr/bin/env node

const fs = require("fs");
const humps = require('humps')

const data = fs.readFileSync(0, "utf-8");
const obj = JSON.parse(data)

console.log(JSON.stringify(humps.camelizeKeys(obj), null, 2))

