#!/usr/bin/env bash

branch_names=("primary" "staging" "master")
for branch_name in "${branch_names[@]}"; do
  if [[ -n `git branch --list $branch_name` ]]; then
     echo "$branch_name"
     exit
  fi
done

echo "default branch not found"
exit 1
