#!/usr/bin/env bash

echo "🚔  rubocoppin"

CHANGED_FILES=$(git diff master... --name-only --diff-filter=ACMRTUXB | xargs)

if bundle exec rubocop --force-exclusion $CHANGED_FILES &> /dev/null; then
  exit
else
  bundle exec rubocop --force-exclusion -a $CHANGED_FILES

  if bundle exec rubocop --force-exclusion $CHANGED_FILES &> /dev/null; then
    echo
    echo "⚠️  Automatically corrected rubocop errors. commit changes and push again."
  else
    echo
    echo "‼️  Could not automatically fix all errors. fix them manually, commit and push again."
    echo
    echo "ensure rubocop will succeed with the following:"
    echo
    echo "bundle exec rubocop --force-exclusion $CHANGED_FILES"
    echo
    echo "or, skip it and run git push --no-verify"
  fi
  echo

  exit 1
fi
