#!/bin/bash

# assumes dyno metadata hero is set up:
# https://devcenter.heroku.com/articles/dyno-metadata
#
# and that heroku is setup to staging / production remotes (https://github.com/schpet/dotfiles/blob/dotfiles/.bin/heroku-remotes)

LOCAL_HASH=$(git rev-parse HEAD)
PRODUCTION_HASH=$(heroku config:get HEROKU_SLUG_COMMIT -r production | sed -e "s/HEROKU_SLUG_COMMIT:[[:space:]]*//")
STAGING_HASH=$(heroku config:get HEROKU_SLUG_COMMIT -r staging | sed -e "s/HEROKU_SLUG_COMMIT:[[:space:]]*//")

ORIGIN=$(git config --get remote.origin.url)

USER=$(echo $ORIGIN | sed -e 's/.*[\/:]\([^/]*\)\/[^/]*$/\1/')
REPO=$(basename $ORIGIN | sed -e "s/\.git$//")

echo "local:      $LOCAL_HASH"
echo "production: $PRODUCTION_HASH"
echo "staging:    $STAGING_HASH"
echo
echo "https://github.com/$USER/$REPO/compare/$PRODUCTION_HASH...$STAGING_HASH"
echo "https://github.com/$USER/$REPO/compare/$PRODUCTION_HASH...$(default-branch)"
