#!/usr/bin/env bash

set -e

DESIGN_URLS=$(tracker-body | jq -r .description |  grep -Eo "(http|https)://www.figma.com[a-zA-Z0-9./?=_%:-]*" | sort -u)

if [[ -z "$DESIGN_URLS" ]]
then 
	echo "no designs in description 🤷🏻‍♂️"
else
	open $DESIGN_URLS
fi
