[nodejs]
symbol = "⬢ "

[username]
disabled = true

[gcloud]
disabled = true

# Custom jj module using starship-jj
[custom.jj]
description = "The current jj status via starship-jj"
when = true
format = "$output"
ignore_timeout = true
command = "starship-jj --ignore-working-copy starship"
use_stdin = false

# Disable git modules when in jj repo
[git_status]
disabled = true

[custom.git_status]
when = "! jj --ignore-working-copy root"
command = "starship module git_status"
style = ""
description = "Only show git_status if we're not in a jj repo"

[git_commit]
disabled = true

[custom.git_commit]
when = "! jj --ignore-working-copy root"
command = "starship module git_commit"
style = ""
description = "Only show git_commit if we're not in a jj repo"

[git_metrics]
disabled = true

[custom.git_metrics]
when = "! jj --ignore-working-copy root"
command = "starship module git_metrics"
description = "Only show git_metrics if we're not in a jj repo"
style = ""

[git_branch]
disabled = true

[custom.git_branch]
when = "! jj --ignore-working-copy root"
command = "starship module git_branch"
description = "Only show git_branch if we're not in a jj repo"
style = ""
